name: sammo543
favicon: null
layout_spectrum: 0.4691483804490417
typography_spectrum: 0.8880662494339049
title: sammo543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#837463'
    - '#a20000'
    - '#ea5000'
    - '#080709'
  brandStrength: 0.8125
  lightness: 0.9090523771010339
  saturation: 0.12033742130734026
  rhythmicContrast: 0.05837895767763257
purpose: []
